<?php
// ============================================================================
// Local data store (SQLite) — for data e-timologio does NOT keep.
// ----------------------------------------------------------------------------
// Multi-tenant: every row is scoped by `account_vat` (the issuing company) so a
// single database file can serve many e-timologio accounts, each with many
// customers. Payments here are LOCAL ONLY — they are never sent to AADE.
//
// Sensitive content (customer name, notes, amounts) is encrypted at rest via
// crypto.php. Identifier/index fields (VATs, dates, method, mark) stay plain so
// the app can still filter and scope. Aggregation is done in PHP after decrypt.
// ============================================================================

require_once __DIR__ . '/crypto.php';

// Which SQL engine backs this instance: 'sqlite' (local/offline) or 'pgsql'
// (central VPS via Coolify). Selected by the DB_DSN config (see below).
function db_dialect(?\PDO $pdo = null): string {
    static $d = null;
    if ($d !== null) return $d;
    $p = $pdo ?? localdb();
    $d = ($p->getAttribute(\PDO::ATTR_DRIVER_NAME) === 'pgsql') ? 'pgsql' : 'sqlite';
    return $d;
}

// Portable "now as 'Y-m-d H:i:s'" SQL expression, used inside DML (INSERT/UPDATE).
function db_now_sql(): string {
    return db_dialect() === 'pgsql'
        ? "to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')"
        : "datetime('now')";
}

// Run an INSERT and return the new id, portably. SQLite uses lastInsertId();
// Postgres appends RETURNING id (identity columns don't expose lastInsertId).
function db_insert(string $sql, array $params): int {
    $pdo = localdb();
    if (db_dialect() === 'pgsql') {
        $st = $pdo->prepare(rtrim($sql) . "\n        RETURNING id");
        $st->execute($params);
        return (int)$st->fetchColumn();
    }
    $st = $pdo->prepare($sql);
    $st->execute($params);
    return (int)$pdo->lastInsertId();
}

function localdb(): \PDO {
    static $pdo = null;
    if ($pdo !== null) return $pdo;

    // Local/offline default = SQLite file; central server sets DB_DSN to a
    // pgsql DSN (+ DB_USER/DB_PASS). One data layer serves both.
    $dsn  = (defined('DB_DSN') && DB_DSN !== '') ? DB_DSN : ('sqlite:' . LOCAL_DB);
    $user = (defined('DB_USER') && DB_USER !== '') ? DB_USER : null;
    $pass = (defined('DB_PASS') && DB_PASS !== '') ? DB_PASS : null;
    $pdo = new \PDO($dsn, $user, $pass);
    $pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
    $pdo->setAttribute(\PDO::ATTR_DEFAULT_FETCH_MODE, \PDO::FETCH_ASSOC);
    $isPg = $pdo->getAttribute(\PDO::ATTR_DRIVER_NAME) === 'pgsql';
    if (!$isPg) $pdo->exec('PRAGMA journal_mode = WAL');

    // DDL translator: the schema below is written in SQLite syntax; for Postgres
    // we swap the two non-portable tokens (identity PK + timestamp default).
    $tr = static function (string $sql) use ($pdo, $isPg) {
        if ($isPg) {
            $sql = str_replace('INTEGER PRIMARY KEY AUTOINCREMENT',
                               'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', $sql);
            $sql = str_replace("(datetime('now'))",
                               "(to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'))", $sql);
        }
        return $pdo->exec($sql);
    };

    // Encrypted fields are stored as TEXT (ciphertext). Index/date fields plain.
    $tr("
        CREATE TABLE IF NOT EXISTS payments (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            account_vat   TEXT NOT NULL,
            customer_vat  TEXT NOT NULL DEFAULT '',
            customer_code TEXT NOT NULL DEFAULT '',
            customer_name TEXT NOT NULL DEFAULT '',   -- encrypted
            amount        TEXT NOT NULL DEFAULT '',    -- encrypted
            method        INTEGER NOT NULL DEFAULT 3,
            pay_date      TEXT NOT NULL,
            mark          TEXT NOT NULL DEFAULT '',
            notes         TEXT NOT NULL DEFAULT '',    -- encrypted
            created_at    TEXT NOT NULL DEFAULT (datetime('now'))
        )
    ");
    $tr("CREATE INDEX IF NOT EXISTS idx_pay_acc_cust ON payments(account_vat, customer_vat)");

    // Encrypted snapshot cache of AADE data (customers/products/invoices) so the
    // UI can render instantly and only re-fetch/compare in the background.
    $tr("
        CREATE TABLE IF NOT EXISTS app_cache (
            account_vat TEXT NOT NULL,
            kind        TEXT NOT NULL,
            payload     TEXT NOT NULL DEFAULT '',  -- encrypted JSON snapshot
            hash        TEXT NOT NULL DEFAULT '',
            synced_at   TEXT NOT NULL DEFAULT (datetime('now')),
            PRIMARY KEY (account_vat, kind)
        )
    ");

    $tr("
        CREATE TABLE IF NOT EXISTS customer_meta (
            account_vat     TEXT NOT NULL,
            customer_vat    TEXT NOT NULL,
            customer_name   TEXT NOT NULL DEFAULT '',  -- encrypted
            opening_balance TEXT NOT NULL DEFAULT '',  -- encrypted
            notes           TEXT NOT NULL DEFAULT '',  -- encrypted
            deliv_meta      TEXT NOT NULL DEFAULT '',  -- encrypted JSON: branch + delivery address
            updated_at      TEXT NOT NULL DEFAULT (datetime('now')),
            PRIMARY KEY (account_vat, customer_vat)
        )
    ");
    // Upgrade path for DBs created before deliv_meta existed.
    try { $tr("ALTER TABLE customer_meta ADD COLUMN deliv_meta TEXT NOT NULL DEFAULT ''"); } catch (\Throwable $e) {}

    // Θεραπεία παλιών πληρωμών: γράφονταν «dd/MM/yyyy» ενώ κάθε φίλτρο συγκρίνει
    // ISO, οπότε δεν εμφανίζονταν ποτέ σε καρτέλα με διάστημα. Μετατρέπονται μία
    // φορά· οι ήδη σωστές δεν ταιριάζουν στο LIKE και μένουν άθικτες.
    try {
        $tr("UPDATE payments
                SET pay_date = substr(pay_date, 7, 4) || '-' || substr(pay_date, 4, 2)
                               || '-' || substr(pay_date, 1, 2)
              WHERE pay_date LIKE '__/__/____'");
    } catch (\Throwable $e) {}

    // Ρυθμίσεις εφαρμογής που ορίζονται από το UI αντί για το config.php:
    // κυρίως τα στοιχεία email (SMTP / Resend). Η τιμή είναι κρυπτογραφημένη —
    // εκεί μέσα ζουν κωδικός SMTP και API key.
    $tr("
        CREATE TABLE IF NOT EXISTS app_settings (
            key        TEXT PRIMARY KEY,
            value      TEXT NOT NULL DEFAULT '',   -- encrypted
            updated_at TEXT NOT NULL DEFAULT (datetime('now'))
        )
    ");

    // --- Auth: application users (master admin + business accounts) ----------
    // email is the login identifier (kept plaintext so it can be queried).
    // role: 'master' | 'business'.  status: 'pending' | 'active' | 'disabled'.
    $tr("
        CREATE TABLE IF NOT EXISTS users (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            email         TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            role          TEXT NOT NULL DEFAULT 'business',
            status        TEXT NOT NULL DEFAULT 'pending',
            business_name TEXT NOT NULL DEFAULT '',
            reset_token   TEXT NOT NULL DEFAULT '',
            reset_expires INTEGER NOT NULL DEFAULT 0,
            totp_secret   TEXT NOT NULL DEFAULT '',   -- encrypted Base32 secret
            totp_enabled  INTEGER NOT NULL DEFAULT 0,
            invited_by    INTEGER NOT NULL DEFAULT 0,
            created_at    TEXT NOT NULL DEFAULT (datetime('now'))
        )
    ");
    // Upgrade path for DBs created before 2FA / invitations / notify-prefs existed.
    foreach ([
        "ALTER TABLE users ADD COLUMN totp_secret TEXT NOT NULL DEFAULT ''",
        "ALTER TABLE users ADD COLUMN totp_enabled INTEGER NOT NULL DEFAULT 0",
        "ALTER TABLE users ADD COLUMN invited_by INTEGER NOT NULL DEFAULT 0",
        "ALTER TABLE users ADD COLUMN notify_prefs TEXT NOT NULL DEFAULT ''",   // encrypted JSON
    ] as $ddl) { try { $tr($ddl); } catch (\Throwable $e) {} }

    // AADE (e-timologio) credentials per business user. vat/label plaintext (used
    // for scoping local data + cookie file + account switching); the e-timologio
    // username and subscription key are encrypted at rest.
    $tr("
        CREATE TABLE IF NOT EXISTS aade_accounts (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id       INTEGER NOT NULL,
            vat           TEXT NOT NULL,
            label         TEXT NOT NULL DEFAULT '',
            username_enc  TEXT NOT NULL DEFAULT '',   -- encrypted
            subkey_enc    TEXT NOT NULL DEFAULT '',   -- encrypted
            created_at    TEXT NOT NULL DEFAULT (datetime('now'))
        )
    ");
    $tr("CREATE INDEX IF NOT EXISTS idx_acc_user ON aade_accounts(user_id)");

    // --- Ανάθεση εταιρειών σε λογιστές ---------------------------------------
    // Ο διαχειριστής βλέπει τα πάντα· ο λογιστής μόνο ό,τι του έχει ανατεθεί.
    // Η ανάθεση ζει εδώ και ΟΧΙ σε στήλη του `aade_accounts`, γιατί μία εταιρεία
    // μπορεί να τη μοιράζονται δύο λογιστές (π.χ. αντικατάσταση σε άδεια).
    $tr("
        CREATE TABLE IF NOT EXISTS account_managers (
            user_id    INTEGER NOT NULL,
            account_id INTEGER NOT NULL,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            PRIMARY KEY (user_id, account_id)
        )
    ");
    $tr("CREATE INDEX IF NOT EXISTS idx_mgr_acc ON account_managers(account_id)");
    manager_seed_existing_editors();

    // --- Scheduled issuance (χρονοπρογραμματισμός) ---------------------------
    // A persistent job store: each row is a παραστατικό (single or bulk) queued
    // to be issued automatically at `run_at`. The `payload` is the ENCRYPTED set
    // of request params the runner replays against the bridge (see scheduler.php).
    // run_at / next_run_at are 'Y-m-d H:i:s' in Europe/Athens local time.
    // status: 'pending' | 'running' | 'done' | 'failed' | 'cancelled'.
    // recurrence: 'none' | 'daily' | 'weekly' | 'monthly'.
    $tr("
        CREATE TABLE IF NOT EXISTS scheduled_jobs (
            id           INTEGER PRIMARY KEY AUTOINCREMENT,
            account_vat  TEXT NOT NULL,
            user_id      INTEGER NOT NULL,
            title        TEXT NOT NULL DEFAULT '',   -- encrypted (human label)
            kind         TEXT NOT NULL DEFAULT 'invoice',
            payload      TEXT NOT NULL DEFAULT '',    -- encrypted JSON of request params
            run_at       TEXT NOT NULL,
            recurrence   TEXT NOT NULL DEFAULT 'none',
            status       TEXT NOT NULL DEFAULT 'pending',
            attempts     INTEGER NOT NULL DEFAULT 0,
            last_run_at  TEXT NOT NULL DEFAULT '',
            last_result  TEXT NOT NULL DEFAULT '',    -- encrypted JSON (mark/aa or error)
            created_at   TEXT NOT NULL DEFAULT (datetime('now'))
        )
    ");
    $tr("CREATE INDEX IF NOT EXISTS idx_sched_due ON scheduled_jobs(status, run_at)");
    $tr("CREATE INDEX IF NOT EXISTS idx_sched_acc ON scheduled_jobs(account_vat)");

    // --- Issuance notifications (ειδοποιήσεις λογιστή/admin) -----------------
    // One row per successfully issued παραστατικό (ΜΑΡΚ obtained), EXCLUDING
    // δελτία αποστολής (9.x). Surfaced to the master admin (all accounts) and to
    // the business itself (own account). Buyer name / amount encrypted at rest.
    $tr("
        CREATE TABLE IF NOT EXISTS issue_notifications (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            account_vat   TEXT NOT NULL,
            actor_user_id INTEGER NOT NULL DEFAULT 0,
            actor_email   TEXT NOT NULL DEFAULT '',
            actor_name    TEXT NOT NULL DEFAULT '',
            doc_type      TEXT NOT NULL DEFAULT '',
            doc_label     TEXT NOT NULL DEFAULT '',
            series        TEXT NOT NULL DEFAULT '',
            aa            TEXT NOT NULL DEFAULT '',
            mark          TEXT NOT NULL DEFAULT '',
            buyer_vat     TEXT NOT NULL DEFAULT '',
            buyer_name    TEXT NOT NULL DEFAULT '',   -- encrypted
            amount_total  TEXT NOT NULL DEFAULT '',    -- encrypted
            source        TEXT NOT NULL DEFAULT 'manual', -- 'manual' | 'scheduled' | 'bulk'
            is_read       INTEGER NOT NULL DEFAULT 0,
            created_at    TEXT NOT NULL DEFAULT (datetime('now'))
        )
    ");
    $tr("CREATE INDEX IF NOT EXISTS idx_notif_acc ON issue_notifications(account_vat, is_read)");

    // --- Κλειδιά σύνδεσης (τοπική εγκατάσταση ↔ web server) ------------------
    // Ο server δίνει ένα κλειδί ανά εταιρεία· η εφαρμογή υπολογιστή το βάζει
    // στις Ρυθμίσεις της και από εκεί και πέρα μιλά με τον server χωρίς να
    // ζητά email/κωδικό σε κάθε βήμα. Αποθηκεύεται ΜΟΝΟ ως sha256: ένα κλειδί
    // που διέρρευσε από τη βάση θα ήταν κλειδί εισόδου στα δεδομένα.
    $tr("
        CREATE TABLE IF NOT EXISTS api_keys (
            id           INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id      INTEGER NOT NULL,
            account_vat  TEXT NOT NULL DEFAULT '',
            label        TEXT NOT NULL DEFAULT '',
            key_hash     TEXT NOT NULL,
            created_at   TEXT NOT NULL DEFAULT (datetime('now')),
            last_used_at TEXT NOT NULL DEFAULT '',
            revoked      INTEGER NOT NULL DEFAULT 0
        )
    ");
    $tr("CREATE INDEX IF NOT EXISTS idx_apikey_hash ON api_keys(key_hash)");

    crypto_backfill_plaintext();

    return $pdo;
}

// --- Εφάπαξ: κρυπτογράφησε ό,τι έμεινε καθαρό -------------------------------
//
// Η enc() έχει «ήπια υποχώρηση»: χωρίς την επέκταση `sodium` επιστρέφει το
// καθαρό κείμενο, ώστε η εφαρμογή να δουλεύει και σε PHP χωρίς αυτήν. Το τίμημα
// είναι ότι μια τέτοια εγκατάσταση έγραφε ΚΑΘΑΡΑ τα διαπιστευτήρια ΑΑΔΕ, τα
// ονόματα πελατών, τα ποσά και τα payload του χρονοπρογραμματιστή — και τα
// δεδομένα αυτά **μένουν** καθαρά όταν αργότερα προστεθεί το sodium, γιατί η
// dec() επιστρέφει αυτούσιο ό,τι δεν αρχίζει με `enc:1:`.
//
// Εδώ κλείνει αυτό το κενό: την πρώτη φορά που η βάση ανοίγει με sodium
// διαθέσιμο, κάθε κρυπτογραφούμενη στήλη που έμεινε καθαρή ξαναγράφεται
// κρυπτογραφημένη. Τρέχει μία φορά (σημαία `crypto.backfilled`), μέσα σε
// συναλλαγή, και **δεν** σημαδεύεται ως ολοκληρωμένη αν κάτι απέτυχε.
function crypto_backfill_plaintext(): void {
    // Χωρίς sodium η enc() θα ξανάγραφε τα ίδια καθαρά δεδομένα: καμία δουλειά,
    // και καμία σημαία — ώστε να τρέξει όταν κάποτε υπάρξει.
    if (!extension_loaded('sodium')) return;
    if (setting_get('crypto.backfilled') === '1') return;

    // πίνακας => [στήλες-κλειδί, στήλες που είναι κρυπτογραφημένες]
    $map = [
        'payments'            => [['id'], ['customer_name', 'amount', 'notes']],
        'app_cache'           => [['account_vat', 'kind'], ['payload']],
        'customer_meta'       => [['account_vat', 'customer_vat'],
                                  ['customer_name', 'opening_balance', 'notes', 'deliv_meta']],
        'app_settings'        => [['key'], ['value']],
        'users'               => [['id'], ['totp_secret', 'notify_prefs']],
        'aade_accounts'       => [['id'], ['username_enc', 'subkey_enc']],
        'scheduled_jobs'      => [['id'], ['title', 'payload', 'last_result']],
        'issue_notifications' => [['id'], ['buyer_name', 'amount_total']],
    ];

    $db = localdb();
    $rewritten = 0;
    try {
        $db->beginTransaction();
        foreach ($map as $table => [$keys, $cols]) {
            foreach ($cols as $col) {
                $sel = $db->prepare('SELECT ' . implode(', ', array_merge($keys, [$col]))
                    . " FROM $table WHERE $col <> '' AND $col NOT LIKE 'enc:1:%'");
                $sel->execute();
                $rows = $sel->fetchAll();
                if (!$rows) continue;
                $where = implode(' AND ', array_map(fn($k) => "$k = :k_$k", $keys));
                $upd = $db->prepare("UPDATE $table SET $col = :v WHERE $where");
                foreach ($rows as $r) {
                    $args = [':v' => enc((string)$r[$col])];
                    foreach ($keys as $k) $args[":k_$k"] = $r[$k];
                    $upd->execute($args);
                    $rewritten++;
                }
            }
        }
        $db->commit();
    } catch (\Throwable $e) {
        if ($db->inTransaction()) $db->rollBack();
        error_log('[etimologio] crypto backfill failed: ' . $e->getMessage());
        return;                       // χωρίς σημαία — ξαναπροσπαθεί στο επόμενο άνοιγμα
    }
    if ($rewritten > 0) error_log('[etimologio] crypto backfill: ' . $rewritten . ' πεδία κρυπτογραφήθηκαν');
    setting_set('crypto.backfilled', '1');
}

// --- Auth: users ------------------------------------------------------------

function user_public(array $r): array {
    return [
        'id'            => (int)$r['id'],
        'email'         => $r['email'],
        'role'          => $r['role'],
        'status'        => $r['status'],
        'business_name' => $r['business_name'],
        'totp_enabled'  => (int)($r['totp_enabled'] ?? 0),
        'created_at'    => $r['created_at'] ?? '',
    ];
}

function user_by_email(string $email): ?array {
    $st = localdb()->prepare("SELECT * FROM users WHERE email = :e");
    $st->execute([':e' => strtolower(trim($email))]);
    return $st->fetch() ?: null;
}

function user_by_id(int $id): ?array {
    $st = localdb()->prepare("SELECT * FROM users WHERE id = :id");
    $st->execute([':id' => $id]);
    return $st->fetch() ?: null;
}

function user_create(string $email, string $passwordHash, string $role, string $status, string $businessName): int {
    return db_insert("
        INSERT INTO users (email, password_hash, role, status, business_name)
        VALUES (:e, :p, :r, :s, :b)
    ", [
        ':e' => strtolower(trim($email)), ':p' => $passwordHash,
        ':r' => $role, ':s' => $status, ':b' => trim($businessName),
    ]);
}

function user_update(int $id, array $fields): void {
    $allowed = ['password_hash', 'role', 'status', 'business_name', 'reset_token', 'reset_expires', 'email', 'totp_secret', 'totp_enabled', 'invited_by'];
    $sets = []; $args = [':id' => $id];
    foreach ($fields as $k => $v) {
        if (!in_array($k, $allowed, true)) continue;
        $sets[] = "$k = :$k"; $args[":$k"] = $v;
    }
    if (!$sets) return;
    $st = localdb()->prepare("UPDATE users SET " . implode(', ', $sets) . " WHERE id = :id");
    $st->execute($args);
}

function users_all(): array {
    $rows = localdb()->query("SELECT * FROM users ORDER BY (role='master') DESC, created_at DESC")->fetchAll();
    return array_map('user_public', $rows);
}

// --- Ρυθμίσεις εφαρμογής -----------------------------------------------------

/**
 * Ολες οι ρυθμίσεις, αποκρυπτογραφημένες, με cache μέσα στο ίδιο request.
 *
 * Το `$reset` το καλεί το setting_set(): χωρίς αυτό, «γράψε και μετά διάβασε»
 * μέσα στο ίδιο request επέστρεφε την ΠΑΛΙΑ τιμή (π.χ. αποθήκευση στοιχείων
 * email και αμέσως δοκιμαστική αποστολή με τον προηγούμενο server).
 */
function settings_all(bool $reset = false): array {
    static $cache = null;
    if ($reset) { $cache = null; return []; }
    if ($cache === null) {
        $cache = [];
        try {
            foreach (localdb()->query("SELECT key, value FROM app_settings") as $r) {
                $cache[$r['key']] = dec($r['value']);
            }
        } catch (\Throwable $e) {
            $cache = [];
        }
    }
    return $cache;
}

/** Μια ρύθμιση, ή `$default` αν δεν έχει οριστεί ποτέ. */
function setting_get(string $key, string $default = ''): string {
    $value = settings_all()[$key] ?? '';
    return $value !== '' ? $value : $default;
}

/** Γράφει (ή σβήνει, με κενή τιμή) μια ρύθμιση. */
function setting_set(string $key, string $value): void {
    $now = db_now_sql();
    $st = localdb()->prepare("
        INSERT INTO app_settings (key, value, updated_at) VALUES (:k, :v, $now)
        ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
    ");
    $st->execute([':k' => $key, ':v' => enc(trim($value))]);
    settings_all(true);   // η cache του request δεν επιτρέπεται να μείνει παλιά
}

function users_count_master(): int {
    return (int)localdb()->query("SELECT COUNT(*) FROM users WHERE role='master'")->fetchColumn();
}

/**
 * Οριστική διαγραφή χρήστη ΜΑΖΙ με τις εταιρείες του.
 *
 * Η απενεργοποίηση κρατά τη γραμμή για πάντα: ένας λογιστής που έφυγε μένει
 * στη λίστα, με τα κρυπτογραφημένα κλειδιά των πελατών του δίπλα. Η διαγραφή
 * αφαιρεί και τα δύο. Οι φύλακες (τελευταίος master, ο εαυτός σου) είναι στο
 * επίπεδο της διαδρομής, όχι εδώ — εδώ γίνεται η πράξη.
 */
function user_delete(int $id): bool {
    $db = localdb();
    $db->prepare("DELETE FROM aade_accounts WHERE user_id = :u")->execute([':u' => $id]);
    $st = $db->prepare("DELETE FROM users WHERE id = :id");
    $st->execute([':id' => $id]);
    return $st->rowCount() > 0;
}

/**
 * Το φίλτρο εταιρείας για ειδοποιήσεις/προγραμματισμό, σε τρεις καταστάσεις.
 *
 * `''` = όλες (διαχειριστής) · μια συμβολοσειρά = μία εταιρεία (επιχείρηση) ·
 * πίνακας = ακριβώς αυτές (λογιστής με ανάθεση). **Άδειος πίνακας σημαίνει
 * καμία** — γι' αυτό γυρίζει `1 = 0` και όχι κενό φίλτρο: το κενό θα άνοιγε
 * ολόκληρη τη βάση σε λογιστή χωρίς ανάθεση.
 */
function db_scope_clause($scope, string $col = 'account_vat'): array {
    if ($scope === '' || $scope === null) return ['', []];
    if (is_array($scope)) {
        $vats = array_values(array_unique(array_filter(array_map('strval', $scope), fn($v) => $v !== '')));
        if (!$vats) return ['1 = 0', []];
        $ph = []; $args = [];
        foreach ($vats as $i => $v) { $ph[] = ":sc$i"; $args[":sc$i"] = $v; }
        return [$col . ' IN (' . implode(',', $ph) . ')', $args];
    }
    return [$col . ' = :sc0', [':sc0' => (string)$scope]];
}

// --- Auth: AADE accounts ----------------------------------------------------

function account_row(array $r): array {
    return [
        'id'       => (int)$r['id'],
        'user_id'  => (int)$r['user_id'],
        'vat'      => $r['vat'],
        'label'    => $r['label'],
        'username' => dec($r['username_enc']),
        'subkey'   => dec($r['subkey_enc']),
        'created_at' => $r['created_at'] ?? '',
    ];
}

function accounts_for_user(int $userId): array {
    $st = localdb()->prepare("SELECT * FROM aade_accounts WHERE user_id = :u ORDER BY id ASC");
    $st->execute([':u' => $userId]);
    return array_map('account_row', $st->fetchAll());
}

// All linked AADE businesses (across every user) — for the master admin's business list.
// The subkey is intentionally omitted (never surfaced to the UI list).
function accounts_all(): array {
    $rows = localdb()->query(
        "SELECT a.*, u.email AS owner_email FROM aade_accounts a LEFT JOIN users u ON u.id = a.user_id ORDER BY a.id ASC"
    )->fetchAll();
    return array_map(function ($r) {
        $a = account_row($r);
        unset($a['subkey']);
        $a['owner_email'] = $r['owner_email'] ?? '';
        // Ποιοι λογιστές τη διαχειρίζονται — το χρειάζεται η οθόνη Διαχείρισης
        // για να δείξει τον διαχωρισμό, όχι απλώς μια λίστα εταιρειών.
        $a['manager_ids'] = account_manager_ids((int)$a['id']);
        return $a;
    }, $rows);
}

// All linked AADE businesses WITH credentials — for internal account resolution
// by staff (accountant/admin) acting on any company. NEVER expose to the UI.
function accounts_all_full(): array {
    $rows = localdb()->query("SELECT * FROM aade_accounts ORDER BY id ASC")->fetchAll();
    return array_map('account_row', $rows);
}

function account_by_vat(string $vat): ?array {
    $vat = preg_replace('/\D/', '', $vat);
    if ($vat === '') return null;
    $st = localdb()->prepare("SELECT * FROM aade_accounts WHERE vat = :v ORDER BY id ASC LIMIT 1");
    $st->execute([':v' => $vat]);
    $r = $st->fetch();
    return $r ? account_row($r) : null;
}

function account_get(int $id): ?array {
    $st = localdb()->prepare("SELECT * FROM aade_accounts WHERE id = :id");
    $st->execute([':id' => $id]);
    $r = $st->fetch();
    return $r ? account_row($r) : null;
}

function account_add(int $userId, string $vat, string $label, string $username, string $subkey): int {
    return db_insert("
        INSERT INTO aade_accounts (user_id, vat, label, username_enc, subkey_enc)
        VALUES (:u, :v, :l, :un, :sk)
    ", [
        ':u' => $userId, ':v' => preg_replace('/\D/', '', $vat), ':l' => trim($label),
        ':un' => enc(trim($username)), ':sk' => enc(trim($subkey)),
    ]);
}

function account_update(int $id, array $d): void {
    $st = localdb()->prepare("
        UPDATE aade_accounts SET vat = :v, label = :l, username_enc = :un, subkey_enc = :sk WHERE id = :id
    ");
    $st->execute([
        ':id' => $id, ':v' => preg_replace('/\D/', '', $d['vat'] ?? ''), ':l' => trim($d['label'] ?? ''),
        ':un' => enc(trim($d['username'] ?? '')), ':sk' => enc(trim($d['subkey'] ?? '')),
    ]);
}

function account_delete(int $id): bool {
    $db = localdb();
    $db->prepare("DELETE FROM account_managers WHERE account_id = :id")->execute([':id' => $id]);
    $st = $db->prepare("DELETE FROM aade_accounts WHERE id = :id");
    $st->execute([':id' => $id]);
    return $st->rowCount() > 0;
}

// --- Ανάθεση εταιρειών σε λογιστές ------------------------------------------
//
// Ο ρόλος «editor» (λογιστής) έβλεπε ΚΑΘΕ εταιρεία της εγκατάστασης. Σε γραφείο
// με πολλούς λογιστές αυτό είναι λάθος: ο καθένας πρέπει να βλέπει μόνο τους
// δικούς του πελάτες. Η ανάθεση είναι **ρητή** — κενή λίστα σημαίνει καμία
// εταιρεία, όχι «όλες». Για να μη χάσει πρόσβαση καμία υπάρχουσα εγκατάσταση,
// το `manager_seed_existing_editors()` τρέχει μία φορά και αναθέτει σε κάθε
// υπάρχοντα λογιστή ό,τι έβλεπε μέχρι τότε (δηλαδή τα πάντα).

/** Τα ids των εταιρειών που έχουν ανατεθεί σε έναν λογιστή. */
function manager_account_ids(int $userId): array {
    $st = localdb()->prepare("SELECT account_id FROM account_managers WHERE user_id = :u ORDER BY account_id ASC");
    $st->execute([':u' => $userId]);
    return array_map('intval', array_column($st->fetchAll(), 'account_id'));
}

/** Οι λογιστές (user ids) που διαχειρίζονται μια εταιρεία. */
function account_manager_ids(int $accountId): array {
    $st = localdb()->prepare("SELECT user_id FROM account_managers WHERE account_id = :a ORDER BY user_id ASC");
    $st->execute([':a' => $accountId]);
    return array_map('intval', array_column($st->fetchAll(), 'user_id'));
}

/** Αντικαθιστά ολόκληρη την ανάθεση ενός λογιστή. */
function manager_set_accounts(int $userId, array $accountIds): void {
    $db = localdb();
    $db->prepare("DELETE FROM account_managers WHERE user_id = :u")->execute([':u' => $userId]);
    $st = $db->prepare("INSERT INTO account_managers (user_id, account_id) VALUES (:u, :a)");
    foreach (array_unique(array_map('intval', $accountIds)) as $aid) {
        if ($aid > 0) $st->execute([':u' => $userId, ':a' => $aid]);
    }
}

/** Αντικαθιστά τους λογιστές μιας εταιρείας (η ίδια σχέση, από την άλλη πλευρά). */
function account_set_managers(int $accountId, array $userIds): void {
    $db = localdb();
    $db->prepare("DELETE FROM account_managers WHERE account_id = :a")->execute([':a' => $accountId]);
    $st = $db->prepare("INSERT INTO account_managers (user_id, account_id) VALUES (:u, :a)");
    foreach (array_unique(array_map('intval', $userIds)) as $uid) {
        if ($uid > 0) $st->execute([':u' => $uid, ':a' => $accountId]);
    }
}

/** Οι εταιρείες ενός λογιστή, ΜΕ διαπιστευτήρια (για την ανάλυση λογαριασμού). */
function accounts_for_manager(int $userId): array {
    $ids = manager_account_ids($userId);
    if (!$ids) return [];
    $in = implode(',', array_fill(0, count($ids), '?'));
    $st = localdb()->prepare("SELECT * FROM aade_accounts WHERE id IN ($in) ORDER BY id ASC");
    $st->execute($ids);
    return array_map('account_row', $st->fetchAll());
}

/**
 * Μία φορά ανά εγκατάσταση: ό,τι έβλεπαν οι λογιστές πριν υπάρξει ανάθεση.
 *
 * Χωρίς αυτό, η αναβάθμιση θα κλείδωνε έξω κάθε λογιστή που δούλευε ήδη.
 */
function manager_seed_existing_editors(): void {
    if (setting_get('managers.seeded') === '1') return;
    setting_set('managers.seeded', '1');
    try {
        $db = localdb();
        $editors = $db->query("SELECT id FROM users WHERE role = 'editor'")->fetchAll();
        if (!$editors) return;
        $accounts = $db->query("SELECT id FROM aade_accounts")->fetchAll();
        if (!$accounts) return;
        $st = $db->prepare("INSERT INTO account_managers (user_id, account_id) VALUES (:u, :a)");
        foreach ($editors as $e) {
            foreach ($accounts as $a) {
                try { $st->execute([':u' => (int)$e['id'], ':a' => (int)$a['id']]); } catch (\Throwable $x) {}
            }
        }
    } catch (\Throwable $e) { /* η ανάθεση δεν είναι λόγος να μη σηκωθεί η βάση */ }
}

// --- Προτιμήσεις UI ανά χρήστη ----------------------------------------------
// Πλάτη και σειρά στηλών ανά πίνακα, φάκελος λήψεων κ.λπ. Ζουν στο `app_settings`
// με πρόθεμα ανά χρήστη: είναι μικρά, σπάνια γράφονται και ταξιδεύουν με τη βάση,
// άρα ο ίδιος χρήστης βρίσκει τη διάταξή του και από άλλον υπολογιστή.
function user_pref_get(int $userId, string $key, string $default = ''): string {
    return setting_get('uipref.' . $userId . '.' . $key, $default);
}

function user_pref_set(int $userId, string $key, string $value): void {
    setting_set('uipref.' . $userId . '.' . $key, $value);
}

/** Όλες οι προτιμήσεις ενός χρήστη, ως χάρτης κλειδί → τιμή. */
function user_prefs_all(int $userId): array {
    $prefix = 'uipref.' . $userId . '.';
    $out = [];
    foreach (settings_all() as $key => $value) {
        if (strncmp($key, $prefix, strlen($prefix)) !== 0) continue;
        $out[substr($key, strlen($prefix))] = $value;
    }
    return $out;
}

// --- Payments ---------------------------------------------------------------

// Map a raw DB row to a decrypted, app-friendly array
function payment_row(array $r): array {
    return [
        'id'            => (int)$r['id'],
        'account_vat'   => $r['account_vat'],
        'customer_vat'  => $r['customer_vat'],
        'customer_code' => $r['customer_code'],
        'customer_name' => dec($r['customer_name']),
        'amount'        => round(dec_num($r['amount']), 2),
        'method'        => (int)$r['method'],
        'pay_date'      => $r['pay_date'],
        'mark'          => $r['mark'],
        'notes'         => dec($r['notes']),
        'created_at'    => $r['created_at'],
    ];
}

function payments_list(string $accountVat, string $customerVat = '', string $from = '', string $to = ''): array {
    $sql = "SELECT * FROM payments WHERE account_vat = :acc";
    $args = [':acc' => $accountVat];
    if ($customerVat !== '') { $sql .= " AND customer_vat = :cv"; $args[':cv'] = $customerVat; }
    if ($from !== '')        { $sql .= " AND pay_date >= :from"; $args[':from'] = $from; }
    if ($to !== '')          { $sql .= " AND pay_date <= :to";   $args[':to']   = $to; }
    $sql .= " ORDER BY pay_date DESC, id DESC";
    $st = localdb()->prepare($sql);
    $st->execute($args);
    return array_map('payment_row', $st->fetchAll());
}

/**
 * Ημερομηνία πληρωμής σε ISO (yyyy-mm-dd) — ό,τι κι αν έστειλε ο πελάτης.
 *
 * Η στήλη `pay_date` συγκρίνεται ως ΚΕΙΜΕΝΟ σε κάθε φίλτρο διαστήματος, οπότε
 * μια αποθηκευμένη «13/08/2026» δεν είναι απλώς άσχημη: είναι αόρατη
 * («13/08/2026» >= «2026-01-01» είναι ψευδές). Ζει εδώ, στο μοναδικό σημείο
 * εισαγωγής, ώστε να μην μπορεί να την προσπεράσει κανένας καλών.
 */
function payment_date_iso(string $value): string {
    $value = trim($value);
    if (preg_match('#^(\d{2})/(\d{2})/(\d{4})#', $value, $m)) return "$m[3]-$m[2]-$m[1]";
    if (preg_match('#^(\d{4})-(\d{2})-(\d{2})#', $value, $m)) return "$m[1]-$m[2]-$m[3]";
    return $value !== '' ? $value : date('Y-m-d');
}

function payment_add(string $accountVat, array $d): int {
    return db_insert("
        INSERT INTO payments (account_vat, customer_vat, customer_code, customer_name, amount, method, pay_date, mark, notes)
        VALUES (:acc, :cv, :cc, :cn, :amt, :m, :dt, :mk, :nt)
    ", [
        ':acc' => $accountVat,
        ':cv'  => trim($d['customer_vat']  ?? ''),
        ':cc'  => trim($d['customer_code'] ?? ''),
        ':cn'  => enc(trim($d['customer_name'] ?? '')),
        ':amt' => enc_num(round((float)($d['amount'] ?? 0), 2)),
        ':m'   => (int)($d['method'] ?? 3),
        ':dt'  => payment_date_iso((string)($d['pay_date'] ?? '')),
        ':mk'  => trim($d['mark'] ?? ''),
        ':nt'  => enc(trim($d['notes'] ?? '')),
    ]);
}

/**
 * Ενημερώνει μια υπάρχουσα πληρωμή. Επιστρέφει false αν δεν ανήκει στον λογαριασμό.
 *
 * Η διαγραφή-και-νέα θα άλλαζε το id της κίνησης· η καρτέλα δείχνει πληρωμές με
 * το id τους, οπότε μια διόρθωση ποσού δεν πρέπει να φτιάχνει άλλη εγγραφή.
 */
function payment_update(string $accountVat, int $id, array $d): bool {
    $st = localdb()->prepare("
        UPDATE payments
           SET customer_vat = :cv, customer_name = :cn, amount = :amt,
               method = :m, pay_date = :dt, notes = :nt
         WHERE account_vat = :acc AND id = :id
    ");
    $st->execute([
        ':acc' => $accountVat,
        ':id'  => $id,
        ':cv'  => trim($d['customer_vat']  ?? ''),
        ':cn'  => enc(trim($d['customer_name'] ?? '')),
        ':amt' => enc_num(round((float)($d['amount'] ?? 0), 2)),
        ':m'   => (int)($d['method'] ?? 3),
        ':dt'  => payment_date_iso((string)($d['pay_date'] ?? '')),
        ':nt'  => enc(trim($d['notes'] ?? '')),
    ]);
    return $st->rowCount() > 0;
}

function payment_delete(string $accountVat, int $id): bool {
    $st = localdb()->prepare("DELETE FROM payments WHERE account_vat = :acc AND id = :id");
    $st->execute([':acc' => $accountVat, ':id' => $id]);
    return $st->rowCount() > 0;
}

function payments_total(string $accountVat, string $customerVat = ''): float {
    $sum = 0.0;
    foreach (payments_list($accountVat, $customerVat) as $p) $sum += $p['amount'];
    return round($sum, 2);
}

// --- Snapshot cache ---------------------------------------------------------

function cache_get(string $accountVat, string $kind): ?array {
    $st = localdb()->prepare("SELECT payload, hash, synced_at FROM app_cache WHERE account_vat = :a AND kind = :k");
    $st->execute([':a' => $accountVat, ':k' => $kind]);
    $r = $st->fetch();
    if (!$r) return null;
    $rows = json_decode(dec($r['payload']), true);
    return ['rows' => is_array($rows) ? $rows : [], 'hash' => $r['hash'], 'synced_at' => $r['synced_at']];
}

function cache_set(string $accountVat, string $kind, array $rows): string {
    $json = json_encode($rows, JSON_UNESCAPED_UNICODE);
    $hash = md5($json);
    $now = db_now_sql();
    $st = localdb()->prepare("
        INSERT INTO app_cache (account_vat, kind, payload, hash, synced_at)
        VALUES (:a, :k, :p, :h, $now)
        ON CONFLICT(account_vat, kind) DO UPDATE SET
            payload = excluded.payload, hash = excluded.hash, synced_at = excluded.synced_at
    ");
    $st->execute([':a' => $accountVat, ':k' => $kind, ':p' => enc($json), ':h' => $hash]);
    return $hash;
}

// --- Customer meta (opening balance + notes) --------------------------------

function customer_meta_get(string $accountVat, string $customerVat): array {
    $st = localdb()->prepare("SELECT * FROM customer_meta WHERE account_vat = :acc AND customer_vat = :cv");
    $st->execute([':acc' => $accountVat, ':cv' => $customerVat]);
    $r = $st->fetch();
    if (!$r) return ['opening_balance' => 0.0, 'notes' => '', 'customer_name' => ''];
    return [
        'customer_name'   => dec($r['customer_name']),
        'opening_balance' => round(dec_num($r['opening_balance']), 2),
        'notes'           => dec($r['notes']),
        'updated_at'      => $r['updated_at'],
    ];
}

function customer_meta_set(string $accountVat, string $customerVat, array $d): void {
    $now = db_now_sql();
    $st = localdb()->prepare("
        INSERT INTO customer_meta (account_vat, customer_vat, customer_name, opening_balance, notes, updated_at)
        VALUES (:acc, :cv, :cn, :ob, :nt, $now)
        ON CONFLICT(account_vat, customer_vat) DO UPDATE SET
            customer_name   = excluded.customer_name,
            opening_balance = excluded.opening_balance,
            notes           = excluded.notes,
            updated_at      = $now
    ");
    $st->execute([
        ':acc' => $accountVat,
        ':cv'  => $customerVat,
        ':cn'  => enc(trim($d['customer_name'] ?? '')),
        ':ob'  => enc_num(round((float)($d['opening_balance'] ?? 0), 2)),
        ':nt'  => enc(trim($d['notes'] ?? '')),
    ]);
}

// --- Per-customer delivery-note settings (branch + delivery address) --------
// Stored as encrypted JSON in customer_meta.deliv_meta so repeat delivery notes
// to the same customer prefill the last-used branch/address. Touches ONLY the
// deliv_meta column (does not disturb opening_balance/notes).

function customer_deliv_get(string $accountVat, string $customerVat): array {
    $st = localdb()->prepare("SELECT deliv_meta FROM customer_meta WHERE account_vat = :acc AND customer_vat = :cv");
    $st->execute([':acc' => $accountVat, ':cv' => $customerVat]);
    $raw = $st->fetchColumn();
    if ($raw === false || $raw === null || $raw === '') return [];
    $json = dec($raw);
    $d = $json !== '' ? json_decode($json, true) : null;
    return is_array($d) ? $d : [];
}

function customer_deliv_set(string $accountVat, string $customerVat, array $d): void {
    $now = db_now_sql();
    $st = localdb()->prepare("
        INSERT INTO customer_meta (account_vat, customer_vat, deliv_meta, updated_at)
        VALUES (:acc, :cv, :dm, $now)
        ON CONFLICT(account_vat, customer_vat) DO UPDATE SET
            deliv_meta = excluded.deliv_meta,
            updated_at = $now
    ");
    $st->execute([
        ':acc' => $accountVat,
        ':cv'  => $customerVat,
        ':dm'  => enc(json_encode($d, JSON_UNESCAPED_UNICODE)),
    ]);
}

// --- Scheduled issuance jobs -------------------------------------------------

function sched_row(array $r): array {
    $result = $r['last_result'] !== '' ? json_decode(dec($r['last_result']), true) : null;
    return [
        'id'          => (int)$r['id'],
        'account_vat' => $r['account_vat'],
        'user_id'     => (int)$r['user_id'],
        'title'       => $r['title'] !== '' ? dec($r['title']) : '',
        'kind'        => $r['kind'],
        'run_at'      => $r['run_at'],
        'recurrence'  => $r['recurrence'],
        'status'      => $r['status'],
        'attempts'    => (int)$r['attempts'],
        'last_run_at' => $r['last_run_at'],
        'last_result' => is_array($result) ? $result : null,
        'created_at'  => $r['created_at'],
    ];
}

function sched_add(string $accountVat, int $userId, array $d): int {
    return db_insert("
        INSERT INTO scheduled_jobs (account_vat, user_id, title, kind, payload, run_at, recurrence, status)
        VALUES (:acc, :uid, :title, :kind, :payload, :run_at, :rec, 'pending')
    ", [
        ':acc'     => $accountVat,
        ':uid'     => $userId,
        ':title'   => enc(trim((string)($d['title'] ?? ''))),
        ':kind'    => trim((string)($d['kind'] ?? 'invoice')),
        ':payload' => enc(json_encode($d['payload'] ?? [], JSON_UNESCAPED_UNICODE)),
        ':run_at'  => trim((string)($d['run_at'] ?? '')),
        ':rec'     => in_array($d['recurrence'] ?? 'none', ['none','daily','weekly','monthly'], true) ? $d['recurrence'] : 'none',
    ]);
}

// List jobs for the UI. Ο διαχειριστής ('' ) βλέπει τα πάντα· ο λογιστής παίρνει
// τη λίστα των εταιρειών του· η επιχείρηση ένα ΑΦΜ.
function sched_list($scope = '', int $limit = 500): array {
    [$where, $args] = db_scope_clause($scope);
    $sql = "SELECT * FROM scheduled_jobs"
         . ($where !== '' ? " WHERE $where" : '')
         . " ORDER BY (status='pending') DESC, run_at DESC LIMIT :l";
    $st = localdb()->prepare($sql);
    foreach ($args as $k => $v) $st->bindValue($k, $v);
    $st->bindValue(':l', $limit, \PDO::PARAM_INT);
    $st->execute();
    return array_map('sched_row', $st->fetchAll());
}

// Full row incl. decrypted payload — used by the runner only.
function sched_get_full(int $id): ?array {
    $st = localdb()->prepare("SELECT * FROM scheduled_jobs WHERE id = :id");
    $st->execute([':id' => $id]);
    $r = $st->fetch();
    if (!$r) return null;
    $out = sched_row($r);
    $out['payload'] = $r['payload'] !== '' ? (json_decode(dec($r['payload']), true) ?: []) : [];
    return $out;
}

// Due jobs across all accounts (runner). $now = 'Y-m-d H:i:s'.
function sched_due(string $now, int $limit = 100): array {
    $st = localdb()->prepare("
        SELECT * FROM scheduled_jobs
        WHERE status = 'pending' AND run_at <= :now
        ORDER BY run_at ASC LIMIT :l
    ");
    $st->bindValue(':now', $now);
    $st->bindValue(':l', $limit, \PDO::PARAM_INT);
    $st->execute();
    return array_map(function ($r) {
        $out = sched_row($r);
        $out['payload'] = $r['payload'] !== '' ? (json_decode(dec($r['payload']), true) ?: []) : [];
        return $out;
    }, $st->fetchAll());
}

function sched_set_status(int $id, string $status): void {
    $st = localdb()->prepare("UPDATE scheduled_jobs SET status = :s WHERE id = :id");
    $st->execute([':s' => $status, ':id' => $id]);
}

// Record a run outcome. If $nextRunAt is given the job is re-queued (recurrence);
// otherwise it lands on the terminal $status ('done' | 'failed').
function sched_record_result(int $id, string $status, array $result, ?string $nextRunAt = null): void {
    if ($nextRunAt !== null) {
        $st = localdb()->prepare("
            UPDATE scheduled_jobs
               SET status='pending', attempts = attempts + 1, last_run_at = :lr,
                   last_result = :res, run_at = :next
             WHERE id = :id
        ");
        $st->execute([
            ':lr' => date('Y-m-d H:i:s'), ':res' => enc(json_encode($result, JSON_UNESCAPED_UNICODE)),
            ':next' => $nextRunAt, ':id' => $id,
        ]);
        return;
    }
    $st = localdb()->prepare("
        UPDATE scheduled_jobs
           SET status = :s, attempts = attempts + 1, last_run_at = :lr, last_result = :res
         WHERE id = :id
    ");
    $st->execute([
        ':s' => $status, ':lr' => date('Y-m-d H:i:s'),
        ':res' => enc(json_encode($result, JSON_UNESCAPED_UNICODE)), ':id' => $id,
    ]);
}

// Cancel a pending job (scoped by account for safety; master passes '' to skip scope).
function sched_cancel(int $id, $scope = ''): bool {
    [$where, $args] = db_scope_clause($scope);
    $sql = "UPDATE scheduled_jobs SET status='cancelled' WHERE id = :id AND status='pending'"
         . ($where !== '' ? " AND $where" : '');
    $st = localdb()->prepare($sql);
    $st->execute($args + [':id' => $id]);
    return $st->rowCount() > 0;
}

/**
 * Οριστική διαγραφή εργασιών που **τελείωσαν** (ακυρωμένες, εκτελεσμένες,
 * αποτυχημένες). Οι εκκρεμείς ΔΕΝ διαγράφονται: πρώτα ακυρώνονται.
 *
 * Χωρίς αυτό η σελίδα γέμιζε με ιστορικό που δεν καθαρίζει ποτέ.
 * ``$id === 0`` σημαίνει «όλες όσες έχουν τελειώσει».
 */
function sched_delete(int $id, $scope = ''): int {
    $done = "status IN ('cancelled','done','failed')";
    $where = $id > 0 ? "id = :id AND $done" : $done;
    $args = $id > 0 ? [':id' => $id] : [];
    [$scopeSql, $scopeArgs] = db_scope_clause($scope);
    if ($scopeSql !== '') {
        $where .= " AND $scopeSql";
        $args += $scopeArgs;
    }
    $st = localdb()->prepare("DELETE FROM scheduled_jobs WHERE $where");
    $st->execute($args);
    return $st->rowCount();
}

// Compute the next run for a recurring job from a base 'Y-m-d H:i:s'. Returns
// null for non-recurring jobs.
function sched_next_run(string $baseRunAt, string $recurrence): ?string {
    if ($recurrence === 'none' || $recurrence === '') return null;
    $ts = strtotime($baseRunAt);
    if ($ts === false) return null;
    $map = ['daily' => '+1 day', 'weekly' => '+1 week', 'monthly' => '+1 month'];
    if (!isset($map[$recurrence])) return null;
    // Advance until strictly in the future so a long-overdue job doesn't fire in a loop.
    $next = $ts;
    $guard = 0;
    do { $next = strtotime($map[$recurrence], $next); $guard++; }
    while ($next !== false && $next <= time() && $guard < 4000);
    return $next ? date('Y-m-d H:i:s', $next) : null;
}

// --- Issuance notifications --------------------------------------------------

function notification_row(array $r): array {
    return [
        'id'           => (int)$r['id'],
        'account_vat'  => $r['account_vat'],
        'actor_email'  => $r['actor_email'],
        'actor_name'   => $r['actor_name'],
        'doc_type'     => $r['doc_type'],
        'doc_label'    => $r['doc_label'],
        'series'       => $r['series'],
        'aa'           => $r['aa'],
        'mark'         => $r['mark'],
        'buyer_vat'    => $r['buyer_vat'],
        'buyer_name'   => $r['buyer_name'] !== '' ? dec($r['buyer_name']) : '',
        'amount_total' => $r['amount_total'] !== '' ? round(dec_num($r['amount_total']), 2) : null,
        'source'       => $r['source'],
        'is_read'      => (int)$r['is_read'],
        'created_at'   => $r['created_at'],
    ];
}

function notification_add(string $accountVat, array $d): int {
    return db_insert("
        INSERT INTO issue_notifications
            (account_vat, actor_user_id, actor_email, actor_name, doc_type, doc_label,
             series, aa, mark, buyer_vat, buyer_name, amount_total, source)
        VALUES (:acc, :uid, :ae, :an, :dt, :dl, :se, :aa, :mk, :bv, :bn, :amt, :src)
    ", [
        ':acc' => $accountVat,
        ':uid' => (int)($d['actor_user_id'] ?? 0),
        ':ae'  => trim((string)($d['actor_email'] ?? '')),
        ':an'  => trim((string)($d['actor_name'] ?? '')),
        ':dt'  => trim((string)($d['doc_type'] ?? '')),
        ':dl'  => trim((string)($d['doc_label'] ?? '')),
        ':se'  => trim((string)($d['series'] ?? '')),
        ':aa'  => trim((string)($d['aa'] ?? '')),
        ':mk'  => trim((string)($d['mark'] ?? '')),
        ':bv'  => trim((string)($d['buyer_vat'] ?? '')),
        ':bn'  => enc(trim((string)($d['buyer_name'] ?? ''))),
        ':amt' => enc_num(round((float)($d['amount_total'] ?? 0), 2)),
        ':src' => trim((string)($d['source'] ?? 'manual')),
    ]);
}

// Master (scope === '') sees all accounts; a business sees its own account; an
// accountant sees exactly the companies assigned to them (array).
// --- Κλειδιά σύνδεσης --------------------------------------------------------

/** Το ορατό κομμάτι ενός κλειδιού — αρκετό για να το αναγνωρίσει ο χειριστής. */
function api_key_mask(string $key): string {
    return strlen($key) > 12 ? (substr($key, 0, 8) . '…' . substr($key, -4)) : '…';
}

/**
 * Νέο κλειδί για έναν χρήστη (και προαιρετικά μία συγκεκριμένη εταιρεία).
 *
 * Επιστρέφει το κλειδί σε ΚΑΘΑΡΗ μορφή — τη μοναδική φορά που υπάρχει. Στη βάση
 * μπαίνει μόνο το sha256 του, οπότε ούτε ο διαχειριστής μπορεί να το ξαναδεί:
 * αν χαθεί, βγάζει καινούριο και ανακαλεί το παλιό.
 */
function api_key_create(int $userId, string $accountVat, string $label): array {
    $key  = 'etk_' . bin2hex(random_bytes(24));
    $id   = db_insert("
        INSERT INTO api_keys (user_id, account_vat, label, key_hash)
        VALUES (:u, :v, :l, :h)
    ", [':u' => $userId, ':v' => preg_replace('/\D/', '', $accountVat),
        ':l' => trim($label), ':h' => hash('sha256', $key)]);
    return ['id' => $id, 'key' => $key, 'masked' => api_key_mask($key)];
}

function api_key_row(array $r): array {
    return [
        'id'           => (int)$r['id'],
        'user_id'      => (int)$r['user_id'],
        'account_vat'  => (string)$r['account_vat'],
        'label'        => (string)$r['label'],
        'created_at'   => (string)$r['created_at'],
        'last_used_at' => (string)$r['last_used_at'],
        'revoked'      => (int)$r['revoked'] === 1,
    ];
}

function api_keys_all(int $userId = 0): array {
    $sql = "SELECT * FROM api_keys";
    $args = [];
    if ($userId > 0) { $sql .= " WHERE user_id = :u"; $args[':u'] = $userId; }
    $sql .= " ORDER BY id DESC";
    $st = localdb()->prepare($sql);
    $st->execute($args);
    return array_map('api_key_row', $st->fetchAll());
}

function api_key_revoke(int $id): bool {
    $st = localdb()->prepare("UPDATE api_keys SET revoked = 1 WHERE id = :id");
    $st->execute([':id' => $id]);
    return $st->rowCount() > 0;
}

/** Το κλειδί → η εγγραφή του, ή null. Ενημερώνει και το «τελευταία χρήση». */
function api_key_resolve(string $key): ?array {
    $key = trim($key);
    if ($key === '') return null;
    $st = localdb()->prepare(
        "SELECT * FROM api_keys WHERE key_hash = :h AND revoked = 0 LIMIT 1");
    $st->execute([':h' => hash('sha256', $key)]);
    $r = $st->fetch();
    if (!$r) return null;
    $now = db_now_sql();
    localdb()->prepare("UPDATE api_keys SET last_used_at = $now WHERE id = :id")
             ->execute([':id' => (int)$r['id']]);
    return api_key_row($r);
}

/**
 * Υπάρχει ήδη ειδοποίηση για αυτό το ΜΑΡΚ;
 *
 * Ο έλεγχος «τι νέο έχει η ΑΑΔΕ» τρέχει σε κάθε σύνδεση: χωρίς αυτό, κάθε
 * σάρωση θα ξαναειδοποιούσε για τα ίδια παραστατικά — και θα ειδοποιούσε ΞΑΝΑ
 * για όσα εκδόθηκαν από την ίδια την εφαρμογή (που έχουν ήδη γραμμή).
 */
function notification_exists(string $accountVat, string $mark): bool {
    if ($mark === '') return false;
    $st = localdb()->prepare(
        "SELECT 1 FROM issue_notifications WHERE account_vat = :a AND mark = :m LIMIT 1");
    $st->execute([':a' => $accountVat, ':m' => $mark]);
    return (bool)$st->fetchColumn();
}

function notifications_list($scope = '', bool $unreadOnly = false, int $limit = 200): array {
    $sql = "SELECT * FROM issue_notifications";
    [$scopeSql, $args] = db_scope_clause($scope);
    $conds = [];
    if ($scopeSql !== '')   { $conds[] = $scopeSql; }
    if ($unreadOnly)        { $conds[] = "is_read = 0"; }
    if ($conds) $sql .= " WHERE " . implode(' AND ', $conds);
    $sql .= " ORDER BY id DESC LIMIT :l";
    $st = localdb()->prepare($sql);
    foreach ($args as $k => $v) $st->bindValue($k, $v);
    $st->bindValue(':l', $limit, \PDO::PARAM_INT);
    $st->execute();
    return array_map('notification_row', $st->fetchAll());
}

function notifications_unread_count($scope = ''): int {
    [$where, $args] = db_scope_clause($scope);
    $sql = "SELECT COUNT(*) FROM issue_notifications WHERE is_read = 0"
         . ($where !== '' ? " AND $where" : '');
    $st = localdb()->prepare($sql);
    $st->execute($args);
    return (int)$st->fetchColumn();
}

function notification_mark_read(int $id, $scope = ''): void {
    [$where, $args] = db_scope_clause($scope);
    $sql = "UPDATE issue_notifications SET is_read = 1 WHERE id = :id"
         . ($where !== '' ? " AND $where" : '');
    $st = localdb()->prepare($sql);
    $st->execute($args + [':id' => $id]);
}

function notifications_mark_all_read($scope = ''): void {
    [$where, $args] = db_scope_clause($scope);
    $sql = "UPDATE issue_notifications SET is_read = 1 WHERE is_read = 0"
         . ($where !== '' ? " AND $where" : '');
    $st = localdb()->prepare($sql);
    $st->execute($args);
}

// --- Per-user email notification preferences (staff/admin) ------------------
// Which companies + movement types a staff member wants EMAILED about. Stored as
// encrypted JSON on the user row. Shape:
//   { email_enabled: bool,
//     companies: ["*"] | ["999999999", …],   // "*"/empty ⇒ all companies
//     types:     ["*"] | subset of invoice|receipt|credit }  // "*"/empty ⇒ all
// Default (unset) = receive everything.
function notify_prefs_default(): array {
    return ['email_enabled' => true, 'companies' => ['*'], 'types' => ['*']];
}

function notify_prefs_get(int $userId): array {
    $st = localdb()->prepare("SELECT notify_prefs FROM users WHERE id = :id");
    $st->execute([':id' => $userId]);
    $raw = $st->fetchColumn();
    if ($raw === false || $raw === null || $raw === '') return notify_prefs_default();
    $json = dec($raw);
    $d = $json !== '' ? json_decode($json, true) : null;
    if (!is_array($d)) return notify_prefs_default();
    return [
        'email_enabled' => array_key_exists('email_enabled', $d) ? (bool)$d['email_enabled'] : true,
        'companies'     => is_array($d['companies'] ?? null) ? array_values($d['companies']) : ['*'],
        'types'         => is_array($d['types'] ?? null) ? array_values($d['types']) : ['*'],
    ];
}

function notify_prefs_set(int $userId, array $prefs): void {
    $clean = [
        'email_enabled' => (bool)($prefs['email_enabled'] ?? true),
        'companies'     => is_array($prefs['companies'] ?? null) && $prefs['companies'] ? array_values(array_map('strval', $prefs['companies'])) : ['*'],
        'types'         => is_array($prefs['types'] ?? null) && $prefs['types'] ? array_values(array_map('strval', $prefs['types'])) : ['*'],
    ];
    $st = localdb()->prepare("UPDATE users SET notify_prefs = :p WHERE id = :id");
    $st->execute([':p' => enc(json_encode($clean, JSON_UNESCAPED_UNICODE)), ':id' => $userId]);
}

// Does a staff member's prefs opt them in to an email for this company + movement?
function notify_prefs_match(array $prefs, string $accountVat, string $category): bool {
    if (empty($prefs['email_enabled'])) return false;
    $companies = $prefs['companies'] ?? ['*'];
    if (!in_array('*', $companies, true) && !in_array($accountVat, $companies, true)) return false;
    $types = $prefs['types'] ?? ['*'];
    if (!in_array('*', $types, true) && !in_array($category, $types, true)) return false;
    return true;
}
